trigger:
- main

pool: 'hh'

jobs:
- job: manage_tf_state_file
  displayName: Manage Terraform State File
  pool: 'hh' #$(agent-pool)
  steps:
  - task: TerraformCLI@1
    displayName: 'check terraform version'
    inputs:
      command: version

  - task: TerraformCLI@1
    displayName: 'Terraform init'
    inputs:
      command: 'init'
       backendServiceArm: 'for-azure-devops'
      backendType: 'azurerm'
      backendAzureRmResourceGroupName: 'azurerm-terraform-rg'
      backendAzureRmStorageAccountName: 'cloudinstitutionbackend1'
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: 'terraform.tfstate'  

  - task: TerraformCLI@1
    displayName: 'Terraform validate'
    inputs:
      command: 'validate'

  - task: TerraformCLI@1
    displayName: 'Terraform plan'
    inputs:
      command: 'plan'
      environmentServiceName: 'for-azure-devops'

  - task: TerraformCLI@1
    displayName: 'Terraform apply'
    inputs:
      command: 'apply'
      environmentServiceName: 'for-azure-devops'
